./../checkdis 1 ../../a/sspexp_codes/pdd/1/label.out.label ../../a/sspexp_codes/pdd/1/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/1_1/label.out.label ../../a/sspexp_codes/pdd/1_1/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/1_4/label.out.label ../../a/sspexp_codes/pdd/1_4/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/2/label.out.label ../../a/sspexp_codes/pdd/2/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/2_1/label.out.label ../../a/sspexp_codes/pdd/2_1/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/2_4/label.out.label ../../a/sspexp_codes/pdd/2_4/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/3/label.out.label ../../a/sspexp_codes/pdd/3/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/3_1/label.out.label ../../a/sspexp_codes/pdd/3_1/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/3_4/label.out.label ../../a/sspexp_codes/pdd/3_4/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/4/label.out.label ../../a/sspexp_codes/pdd/4/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/4_1/label.out.label ../../a/sspexp_codes/pdd/4_1/query.out
./../checkdis 1 ../../a/sspexp_codes/pdd/4_4/label.out.label ../../a/sspexp_codes/pdd/4_4/query.out
